using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Robowire.RobOrm.Core.Migration
{
    public interface IMigrationScriptBuilder
    {
        void CreateTable(string tableName, string pkColumnName, Type pkColumnType, bool pkAutogenerated);

        void CreateColumn(
            string tableName,
            string columnName,
            string columnType,
            bool allowsNulls,
            bool unique);

        void CreateForeignKey(
            string referringTableName,
            string referringColumnName,
            string referredTableName,
            string referredColumnName);
    }
}
