using System;
using System.Collections.Generic;

namespace Robowire.RobOrm.Core.EntityModel
{
    public interface IEntity
    {
        string DbEntityName { get; }

        bool IsDirty { get; }

        object PrimaryKeyValue { get; set; }

        Type PrimaryKeyType { get; }

        bool IsPrimaryKeyAutogenerated { get; }

        void ReadSelf(IDataRecord row);

        bool ReadPrimaryKey(IDataRecord reader);

        IEnumerable<Tuple<string, Type>> GetReferenceProperties();

        IEntitySet OpenProperty(string propertyName);

        SaveMethodType GetSaveMethodType();

        IEnumerable<EntityColumnValue> GetValues();
    }
}